manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: gpeye
      url-base: https://github.com/GPeye
    - name: rumatoest
      url-base: https://github.com/rumatoest
    - name: englmaxi
      url-base: https://github.com/englmaxi
  projects:
    - name: mario-peripheral-animation
      remote: gpeye
      revision: main 
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: prospector-zmk-module                # <--- and these
      remote: rumatoest                          # <---
      revision: tokyo2006-micro_spi2  
    - name: zmk-dongle-display
      remote: englmaxi
      revision: v0.3
  self:
    path: config
